version: 2

workflows:
  version: 2
  crostini:
    jobs:
      - test

jobs:
  test:
    working_directory: ~/crostini
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: v1-graphql-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - save_cache:
          key: v1-graphql-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /tmp/.yarn_cache
      - run: npm run prettier:check
      - run: npm run tsc
      - run: npm run check-json
      - run: npm run mocha
